














defaults:
  - _self_

  - model: cvt_pyramid_axial  # <- 필요한 모델 config 참조
  - data: nuscenes.yaml 
  - visualization: null

  - loss: default_loss
  - metrics: default_metrics

experiment:
  project: cross_view_transformers_pyramid_axial
  uuid: ${now:%m%d_%H%M%S}
  save_dir: ${hydra:runtime.cwd}/logs/

  seed: 2022
  checkpoint_interval: 1000
  log_image_interval: 500

loader:
  batch_size: 4  #원래 8
  num_workers: 2 #원래 32
  pin_memory: True
  prefetch_factor: 4

  # OneCycleLR
scheduler:
  div_factor: 10
  pct_start: 0.3
  final_div_factor: 10

  max_lr: ${optimizer.lr}
  total_steps: ${trainer.max_steps}
  cycle_momentum: False

# lightning trainer
trainer:
  max_steps: 50000
  log_every_n_steps: 50

  gpus: -1
  precision: 16 #원래 32

  limit_train_batches: 1.0
  limit_val_batches: 1.0
  gradient_clip_val: 5.0
  sync_batchnorm: False
